language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services

script:
 - ./gradlew clean build
  